### ISSUE TITLE
Error in rule build_qc_report

### ISSUE THREAD

**Issue by bobems1215** [metagenome-atlas/atlas#174]
I have been having an issue running atlas on my data on a computing cluster. When I run atlas it gets to 54% complete and crashes out on step 436. Additionally I get an error that states "ValueError: Invalid file path or buffer object type: <class 'NoneType'>"  followed by "CalledProcessError in line 586 of ~/qc.snakefile". 

I have seen the ValueError in other programs and it think its related to Pandas? However since everything is anaconda based I don't think this is the issue. 

Thanks,

Bob

**Comment by SilasK** [comment]
This is more tricky.  It seems a problem in the `build_qc_report`rule, which calls a python script that uses a pandas. 
Invalid file path, could mean that one of the input files is empty. 

Can you give more information about the bug: 

what you can try:

run:
```atlas run None build_qc_report -p --debug ```

This runs the only this rule which creates the bug. You can run it locally (It doesn't use a lot of ressources). 

the log should print the sehell command executed, something like:

```
activate conda environement complicated/path/to/conda/env
python {params.snakefile_folder}/report/qc_report.py \
            --samples {params.samples} \
            --report_out {output.report} \
            --zipfiles_QC {input.zipfiles_QC} \
            --zipfiles_raw {input.zipfiles_raw} \
            --min_quality {params.min_quality} \
            --read_counts {input.read_counts}


```

You can then, go to *your workig directory*, and execute these commands:

```
source activate environement complicated/path/to/conda/env # or conda activate
python {params.snakefile_folder}/report/qc_report.py \
            --samples {params.samples} \
            --report_out {output.report} \
            --zipfiles_QC {input.zipfiles_QC} \
            --zipfiles_raw {input.zipfiles_raw} \
            --min_quality {params.min_quality} \
            --read_counts {input.read_counts}
```

**Comment by bobems1215** [comment]
Thank you for all the info!. So I am trying to run 
`atlas run None build_qc_report -p --debug`

But I keep getting an error "Error: debug mode cannot be used with more than one core or cluster execution." So I am running atlas on our cluster but I dont know how to run this command only on one core.  Is there something that I should be changing in the config.yaml file? 

Thanks again.

**Comment by SilasK** [comment]
You can add '-j 1'

**Comment by dtnaylor124** [comment]
I am also having this issue. I tried debugging as described above, I don't know if it really did anything. For reference here's the complete error message:

^[[33mJob counts:
        count   jobs
        1	get_contigs_from_gene_names
        1^[[0m
[Thu Feb 14 11:24:50 2019]
Finished job 137.
7 of 164 steps (4%) done
Traceback (most recent call last):
  File "/home/nayl574/miniconda3/envs/dan_test_env/lib/python3.6/site-packages/atlas/report/qc_report.py", line 269, in <module>
    main(**vars(args))
  File "/home/nayl574/miniconda3/envs/dan_test_env/lib/python3.6/site-packages/atlas/report/qc_report.py", line 127, in main
    df = pd.read_table(read_counts, index_col=[0, 1])
  File "/home/nayl574/databases/conda_envs/fa33b612/lib/python3.6/site-packages/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/nayl574/databases/conda_envs/fa33b612/lib/python3.6/site-packages/pandas/io/parsers.py", line 392, in _read
    filepath_or_buffer, encoding, compression)
  File "/home/nayl574/databases/conda_envs/fa33b612/lib/python3.6/site-packages/pandas/io/common.py", line 210, in get_filepath_or_buffer
    raise ValueError(msg.format(_type=type(filepath_or_buffer)))
ValueError: Invalid file path or buffer object type: <class 'NoneType'>
[Thu Feb 14 11:24:53 2019]
Error in rule build_qc_report:
    jobid: 12
    output: reports/QC_report.html
    conda-env: /home/nayl574/databases/conda_envs/fa33b612

RuleException:
CalledProcessError in line 587 of /home/nayl574/miniconda3/envs/dan_test_env/lib/python3.6/site-packages/atlas/rules/qc.snakefile:
Command 'source activate /home/nayl574/databases/conda_envs/fa33b612; set -euo pipefail;
         python /home/nayl574/miniconda3/envs/dan_test_env/lib/python3.6/site-packages/atlas/report/qc_report.py             --samples ['SP-5-001' 'SP-4-001' 'SP-9-001' 'SP-6-001' 'SP-1-001' 'SP-2-001'
 'SP-3-001']             --report_out reports/QC_report.html             --zipfiles_QC SP-5-001/sequence_quality_control/read_stats/QC.zip SP-4-001/sequence_quality_control/read_stats/QC.zip SP-9-001/sequence_quality_c$
  File "/home/nayl574/miniconda3/envs/dan_test_env/lib/python3.6/site-packages/atlas/rules/qc.snakefile", line 587, in __rule_build_qc_report
  File "/home/nayl574/miniconda3/envs/dan_test_env/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message


Thanks for any help you can provide!

**Comment by SilasK** [comment]
It seems it can not open the file `stats/read_counts.tsv`. Does it exist? has it data in it? 
If not you can delete it and rerun atlas. 

The file should look like this for one sample. 

Sample | Step | Total_Reads | Total_Bases | Reads_pe | Bases_pe | Reads_se | Bases_se | Timestamp
-- | -- | -- | -- | -- | -- | -- | -- | --
S005 | raw | 933 | 275744 | 933 | 275744 | 0 | 0 | 2019-02-19-08:08:30
S005 | deduplicated | 933 | 275744 | 933 | 275744 | 0 | 0 | 2019-02-19-08:08:32
S005 | filtered | 933 | 275600 | 933 | 275600 | 0 | 0 | 2019-02-19-08:09:00
S005 | clean | 933 | 275600 | 933 | 275600 | 0 | 0 | 2019-02-19-08:09:08
S005 | QC | 933 | 275600 | 933 | 275600 | 0 | 0 | 2019-02-19-08:09:09

**Comment by dtnaylor124** [comment]
It certainly exists, and has data in it comparable to what you have above.

**Comment by SilasK** [comment]
Could you send me the snakemake log file. The path to it appears after each (errenous ) run. 

In the mean time you can continue the run with `-k` command argument.

**Comment by dtnaylor124** [comment]
Attached!

[2019-02-19T191704.435494.snakemake.log](https://github.com/metagenome-atlas/atlas/files/2885713/2019-02-19T191704.435494.snakemake.log)

**Comment by SilasK** [comment]
I cannot reporoduce your error. 

Can you run the command below in the *atlas working directory*. And try to find why the file stats/read_counts.tsv is not correclty passed to the script. 

```
source activate /home/nayl574/databases/conda_envs/fa33b612; set -euo pipefail;  
python /home/nayl574/miniconda3/envs/dan_test_env/lib/python3.6/site-packages/atlas/report/qc_report.py             --samples ['SP-5-001' 'SP-4-001' 'SP-9-001' 'SP-6-001' 'SP-1-001' 'SP-2-001' 'SP-3-001']             --report_out reports/QC_report.html             --zipfiles_QC SP-5-001/sequence_quality_control/read_stats/QC.zip SP-4-001/sequence_quality_control/read_stats/QC.zip SP-9-001/sequence_quality_control/read_stats/QC.zip SP-6-001/sequence_quality_control/read_stats/QC.zip SP-1-001/sequence_quality_control/read_stats/QC.zip SP-2-001/sequence_quality_control/read_stats/QC.zip SP-3-001/sequence_quality_control/read_stats/QC.zip             --zipfiles_raw SP-5-001/sequence_quality_control/read_stats/raw.zip SP-4-001/sequence_quality_control/read_stats/raw.zip SP-9-001/sequence_quality_control/read_stats/raw.zip SP-6-001/sequence_quality_control/read_stats/raw.zip SP-1-001/sequence_quality_control/read_stats/raw.zip SP-2-001/sequence_quality_control/read_stats/raw.zip SP-3-001/sequence_quality_control/read_stats/raw.zip             --min_quality 10             --read_counts stats/read_counts.tsv
```

**Comment by dtnaylor124** [comment]
That command seemed to work fine - the QC report is attached - but I'm not sure why it's not recognizing the "stats/read_counts.tsv" extension as legitimate. Is it a pandas issue?

[ATLAS - QC Summary.pdf](https://github.com/metagenome-atlas/atlas/files/2891155/ATLAS.-.QC.Summary.pdf)

**Comment by SilasK** [comment]
The output was a html and you transfomed it to a pdf, right? Can you now
continue atlas?

Wich snakemake version are you using?

**Comment by dtnaylor124** [comment]
That's right! ATLAS does seem to be running again now that the QC report was generated manually. If this proves to be a stumbling block in the future I'll be sure to let you know. Thanks!

Also, I'm using snakemake 5.4.0.

**Comment by SilasK** [comment]
Ok don't hesitate to re-open the issue.
