### ISSUE TITLE
cat_on_bin step not working correctly

### ISSUE THREAD

**Issue by dtnaylor124** [metagenome-atlas/atlas#199]
I'm running the cat_on_bin step and it appears to be generating a version of the concatenated.fasta file that appears to be truly massive in terms of file size (currently at 643 GB with no end in sight). I'm attaching my log files but I don't think they'll be helpful as they're not reporting any error. Any idea what might be going wrong / what I can do to resolve this issue? Thanks!

[error_04102019.txt](https://github.com/metagenome-atlas/atlas/files/3065758/error_04102019.txt)

[MAG1.log](https://github.com/metagenome-atlas/atlas/files/3065753/MAG1.log)

**Comment by SilasK** [comment]
The concatenated.fasta should be the predicted genes with prodigal. I don’t know why the translated ORFs of your MAG1 fill several gigabytes. Its a normal prokaryote genome? The size of the contigs is more or less what you expect? You can test the length with “stats.sh MAG1.fasta” from bbmap.

May be you can test to run ‘atlas run None "genomes/annotations/genes” ‘ which runs also prodigal. To see if the problem is with prodigal or within CAT.

**Comment by dtnaylor124** [comment]
The length of the contigs in MAG1.fasta was about 8 MB, so I can't see why the genes would be so long.

Trying to run prodigal as you described above unfortunately didn't do anything, just giving the below message:

Building DAG of jobs...
Updating job 0.
Nothing to be done.

**Comment by SilasK** [comment]
Does the file genomes/annotations/genes/MAG1.fasta already exist ?

Which version of Atlas are you using?

**Comment by dtnaylor124** [comment]
The MAG1.fasta file in that folder doesn't exist, there is a MAG1.faa (and .fna and .gff) in that folder however. I'm using the recent 2.0.7 version of ATLAS.

**Comment by SilasK** [comment]
Ok, this means the problem i not with prodigal gene prediction.

**Comment by SilasK** [comment]
Hmm, It seems to be a problem with CAT.

@bastiaanvonmeijenfeldt do you have an idea how to solve this bug?


You are shure it's the concatenated fasta which is too heavy?

Because there are many databases files for CAT or eggNOG which are expected to weight several gb.

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @SilasK,

Indeed a concatenated fasta file of 600GB for a single MAG is way too large for a prokaryotic genome! I suspect this happened here since both the bin suffix and concatenated fasta are `.fasta` and you're writing the concatenated fasta to the bin folder, hence the file might keep on opening and writing itself. I will try to push a fix today or tomorrow. I will also make work of the 'single bin' mode soon.
Thanks for finding this out and I'm sorry for the inconvenience!

Best wishes,

Bastiaan

**Comment by bastiaanvonmeijenfeldt** [comment]
I have updated CAT to v4.5, and have not only added single bin mode but have also changed the way in which concatenated fasta files are made. So the newest version provides two possible solutions for this bug:
1) Running BAT in single bin mode on this MAG will just skip the concatenated fasta file altogether (the concatenated files are only necessary for multiple bin mode).
2) If you would run BAT in multiple bin mode like you did here with the newest version, I think the issue is solved as well because of the new way I generate the concatenated files.

Bus as I said, I couldn't replicate the bug myself (and would really like to know where it came from to see if I have truly fixed it in the latest release). @dtnaylor124 could you tell me which files were in your bin folder and in your output folder before running BAT? And also which where there after?

Best wishes,

Bastiaan

**Comment by dtnaylor124** [comment]
I assume the bin folder refers to the genomes/genomes folder? That contains all the .fasta files for the MAGs (MAG1.fasta - MAG9.fasta) and nothing else. In the output folder (genomes/taxonomy/MAG1), before running that CAT step I have the .faa and .gff files for the concatenated.predicted_proteins for MAG1; after running it (or while it's running, as it hasn't completed yet) I get the MAG1.fasta and MAG1.concatenated.fasta files. I don't get the other files that I assume are part of that step (extensions 'bin2classification.txt', 'concatenated.alignment.diamond', 'ORF2LCA.txt', 'log').

**Comment by mdehollander** [comment]
Did the CAT `v4.5` release fix this issue? I ran into the same issue again, although with a older version of ATLAS (`5.0.4`, see https://github.com/metagenome-atlas/atlas/issues/217#issuecomment-513717596 for more info). In the current master branch the CAT version hasn't been updated yet: https://github.com/metagenome-atlas/atlas/blob/master/atlas/envs/cat.yaml#L6

**Comment by SilasK** [comment]
Last time when I checked, the newest Cat version was not yet on Conda.
I solved the problem by putting each genome in a separate subdirectories. For this is the rule get_genome_for_cat.
But then we are back to the checkpoint issue.

**Comment by SilasK** [comment]
Do you need cat annotation or would be the taxonomy from checkm be enough?

**Comment by mdehollander** [comment]
I can say that ATLAS v2.0.5 and CAT version 4.6 works perfectly. The MAGs are now classified, without huge `.concatenated.fasta` files being created.

**Comment by SilasK** [comment]
I updated the CAt version in the master branch
