### ISSUE TITLE
Is it possible to use Atlas in nanopore sequencing data?

### ISSUE THREAD

**Issue by maithemagalhaes** [metagenome-atlas/atlas#273]

**Comment by SilasK** [comment]
Thank you for the question. 
You can do a hybrid assembly (ilumina + nanopore) using spades. 

I don't have experience of nanopore assembly alone. 
Maybe we can adapt atlas to work also for long reads alone. 

E.g.  If you have MAG predicted you can use atlas to do the taxonomic and functional annotation.

**Comment by botellaflotante** [comment]
is it possible to run ATLAS with Illumina mate-pair reads?

**Comment by SilasK** [comment]
As I understand,  mate-pair libraries can be mapped as normal paire-end libraries.
It seems spades supports mate-pair libraries. So with a small adaption, Atlas could support mate pair libraries. 
However, I don't know if you have to do some special quality control before.

**Comment by botellaflotante** [comment]
I actually have a single end set of reads and also a small mate pair set of reads for the same sample, but I don't know if I can change the config file to take these... I guess ATLAS is normally used for paired.end, right?

**Comment by SilasK** [comment]
Ok then you could do it the following:

Start Atlas with the single end read library `atlas init` .


Set `spades_preset: normal ` in the config file to use normal spades.

Metaspades doesn't allow mate pairs nor single end reads, but I've heard that normal spades is almost as good as metaspades for metagenome assembly. 

you can pass extra arguments to spades via the `spades_extra` keyword in the config file.
See the documentation of spades for how to do this: https://github.com/ablab/spades#input-data

e.g with matepairs this would be something like:

```
spades_extra: " --mp1-1 path/to/matepair_R1.fastq --mp1-2 path/to/matepair_R2.fastq"
```

**Comment by botellaflotante** [comment]
It worked fine mostly, although there is some issue in the maxbin step... (so I have no bins and no genomes). 
Not sure where to spot the exact problem though

**Comment by SilasK** [comment]
Many users have encountered the problem that maxbin doesn't produce bins. Maybe the assembly is to complicated. Did metabat produce bins? Then you might just set `final_binner: metabat`

In your particular case, it might be due to the fact that only the SE reads are used for mapping and that you have less coverage for binning.

**Comment by botellaflotante** [comment]
yes, it worked. Thanks!

**Comment by rhysnewell** [comment]
Hi @SilasK,
I was just wondering if you could clarify how you specify both long and short-read inputs during `atlas init` there doesn't seem to be an option to differentiate between long and short-read input (atlas v2.8.2 conda-forge)
Cheers,
Rhys

**Comment by SilasK** [comment]
Atlas can handle long reads + short reads. ([see the docs](https://metagenome-atlas.readthedocs.io/en/latest/usage/configuration.html#long-reads))

But I'm thinking about developing something for long reads only, is that what you want?

**Comment by rhysnewell** [comment]
Cool, thanks nah I was looking for hybrid assembly options. Not long read independently 

I guess I was hoping for a command-line option to specify my input reads. I've got a large amount of metagenomes to assemble that have both short and long reads, setting up config files for each of them is going to get tedious. That's okay, thanks for your response

**Comment by SilasK** [comment]
Do your long read files contain the sample name in the filename?

**Comment by SilasK** [comment]
Hey @rhysnewell I made a function to add the long reads to the atlas sample table.
This [function](https://gist.github.com/SilasK/f95a2efdacb277145e878f95dcc0a497) should allow you to add the long reads to the sample table.

You might need to install

`mamba install -y pathlib2`

From within the atlas folder run
`import_long_reads.py ../../pacbio` 

I run a test and it worked for me. However your sample names become something very long with dots in it. I suggest you to replace them with something simpler. 


Try it out, if it works, I add it to the init function.

**Comment by SilasK** [comment]
By the way, how was your experience with muffin? 

Do you have hiFi pacbio reads or long reads with lower quality? In the case of hifi reads, there should be dedicated assemblers? Also something I like to add to atlas.

**Comment by AstrobioMike** [comment]
hey there, @SilasK :) 

thanks for your work here!

I came across someone looking for a workflow suitable for solely nanopore data and found my way to this issue. It looks like maybe this has stopped here for now due to a lack of need/priority so far, but just wanna check with 2 quick questions:

1. Has taking solely long reads as input been integrated into the main program yet as discussed above?
2. If yes, when solely nanopore reads are provided, is an assembler used that is specifically designed for dealing with them/their higher error rates (e.g. like [flye has settings for](https://github.com/fenderglass/Flye/blob/flye/docs/USAGE.md#-supported-input-data) or something else)?

thanks!

**Comment by SilasK** [comment]
@AstrobioMike It is not implemented in the main workflow, but I would be happy to help to make it happen. 

As alternative for now I suggest MUFFIN.

**Comment by AstrobioMike** [comment]
Oh excellent, thanks for the note about muffin, I will pass that along 🙂

No specific pressure from me to integrate a long-read specific path here, especially since you pointed out muffin seems to already have a way

Actually I just looked a bit and it seems muffin might require short reads also. I have a question in to them making sure, but if that is the case, maybe there is still a niche to fill for a general workflow starting with long reads only and it might be worth it to add some things in here for that capability if you make the time/find the motivation 

Thanks again!

**Comment by jmtsuji** [comment]
Just to add a comment to this thread, I've been working on a snakemake workflow for microbial genome assembly/annotation using Nanopore data -- it can perform either a long-read only or a hybrid long/short read workflow. The basic framework could probably be adapted and added into ATLAS for long-read only metagenome assembly, if there were interest. See https://github.com/jmtsuji/rotary (still in development!)

Sorry for generally being slow to reply these days! Thanks again for all your work on ATLAS!
