### ISSUE TITLE
unable to open database file

### ISSUE THREAD

**Issue by canaanwc** [metagenome-atlas/atlas#291]
Hi,
I am trying to run atlas run binning. I keep getting the same error. 

**Activating conda environment: /scratch/user/my_atlas_workflow/databases/conda_envs/6e78d9f0
Error: near line 1: unable to open database file
Error in rule maxbin:
    jobid: 109
    output: my_sample/binning/maxbin/intermediate_files
    log: my_sample/logs/binning/maxbin.log (check log file(s) for error message)**

and when I check the log file it says....

**Running FragGeneScan....
Error running FragGeneScan. Output recorded in my_sample/binning/maxbin/intermediate_files/my_sample.contig.tmp.frag.out and my_sample/binning/maxbin/intermediate_files/my_sample.contig.tmp.frag.err.
=== Please make sure that you are running FragGeneScan 1.18 or above. ===
=== There are known bugs in v1.17 and before that will crash FragGeneScan program. ===**

Any help would be much appreciated.
Thanks!

**Comment by SilasK** [comment]
Sorry, for responding so late. 

what's the content of the files:
`my_sample/binning/maxbin/intermediate_files/my_sample.contig.tmp.frag.err``
`my_sample/binning/maxbin/intermediate_files/my_sample.contig.tmp.frag.out`

I assume the problems are not related to incompatible versions because the package is maintained by bioconda unless you work on MacOS. 

- Maybe the assembly is too small, and cannot be binned? 
    Do you have any sample which passes the maxbin or the metabat step? 
    `Results are in {sample}/binning`
