### ISSUE TITLE
default maping rate with bbmap is 0.76

### ISSUE THREAD

**Issue by SilasK** [metagenome-atlas/atlas#303]
I realized that the default min mapping id is set to, which corresponds to the default of bbmap but is very low for metagenomic reads mapping. I usually use 0.9.

@jmtsuji do you have any experience with different mapping rates?  

 `contig_min_id: 0.76`

**Comment by jmtsuji** [comment]
@SilasK I've done a little work on optimizing the min mapping ID threshold, but nothing particularly comprehensive. I found that 0.76 can cause cross-over read mapping between related bins, especially because the bbmap default is to map reads to the 10 closest matches above the ID threshold. These days, I set the min mapping ID to 0.95 and seem to get good specificity. I also check sometimes for how many reads were mapped to more than one location as a measure of whether cross-over read mapping is happening.

E.g., in our [recent ISME J paper using ATLAS2](https://www.nature.com/articles/s41396-020-0650-2):
> Multiple comammox Nitrospira populations were found in the same RBC, and such high diversity of comammox Nitrospira contrasts with the observed low AOA diversity (i.e., only one Nitrosocosmicus species; see below) for all RBCs sampled. Although 0.5–3.1% (median 1.1%) of assembled reads associated with Nitrospira MAGs were mapped to more than one MAG (data not shown), this level of crossover read mapping is insufficient to explain the high observed diversity of comammox Nitrospira for most RBCs, meaning that the high observed diversity is likely not an artifact of read mapping.

However, I haven't checked how sensitive 0.95 is (i.e., whether or not we are missing data when we map). I think setting the default to 0.9 as you've done seems reasonable, until more detailed study of read mapping percentages can be done.

**Comment by SilasK** [comment]
Great thank you very much for your experience. 

Congratulations on your article. I think I should start listing the publication using atlas.

Have you tried to use the bbmap 'best' mode to map a read only to the first best location?

**Comment by jmtsuji** [comment]
@SilasK Thanks! I haven't tried using the 'best' mode but think it would be good to explore as the default setting for ATLAS. Using the 'best' mode could reduce noise in read mapping data.

I'd be okay to contribute to a publication list if you made one.
