### ISSUE TITLE
Line-length-limit error when trying to open the QC_report html file

### ISSUE THREAD

**Issue by slambrechts** [metagenome-atlas/atlas#380]
Hi,

I'm getting a weird error when trying to open the QC report: 

> System Message: ERROR/3 ()
> 
> Line 62 exceeds the line-length-limit.

chrome, firefox, ie, edge all gave the same error

Should I open the atlas html reports with something else or is this a bug?

**Comment by SilasK** [comment]
It's probably a but I haven't heard of. I'm about to recode the reports with a new version of plotly #354 which hopefully should solve the issue. 

You could try to open the HTML in a text editor and see what's on line 63, maybe you can add a linebreak without disrupting the code. 

Otherwise there are tables in the stats folder, have a look at them.
