### ISSUE TITLE
vamb doesn't have access to shared libraries

### ISSUE THREAD

**Issue by SilasK** [metagenome-atlas/atlas#450]
After successful testing on my home server I have several problems on a new server. 

Error with Vamb 3.0.3 intalled in a conda env with pip.

I got the error: `ImportError: libimf.so: cannot open shared object file: No such file or directory`

It seems to me that the way we install vamb doesn't deal with all the dependencies. 

I also saw that vam 3.0.1 needed python 3.7 by default now python 3.9 is installed. 
After changing that I got an other error related to another shared library. 

Googling showed me a potential link with the setuptools. And as vamb uses an obsolete setuptools I think this could be the reason. 

Can't we go back to vamb 3.0.1 installed with vamb for the time being?  @yanhui09

**Comment by SilasK** [comment]
Asking differently what would we need to change to again be able to use vamb 3.0.1?

**Comment by yanhui09** [comment]
Did the error appear in building the conda env? I have just tried it in my `ubuntu` server, and it complete the installation successfully, and correct python version (`3.7.10`) is installed as defined. Previous tests were done on a public server in Denmark. 
```
ImportError: libimf.so: cannot open shared object file: No such file or directory
``` 
I googled this error, it seems to be associated with the linux distributions, rather than the software itself.  https://github.com/itsmeludo/PhylOligo/issues/6
Probably `LD_LIBRARY_PATH` is not assigned correctly on the server?

For previous versions of  `vamb`, I only have experience to install it from conda channel. I haven't tested it recently. At least for `vamb 3.0.2`, the conda version couldn't solve the dependency perfectly, probably because the loose dependency setting couldn't make a correct selection among the updated packages.

**Comment by yanhui09** [comment]
You may ask for a version change with pip?
Change the line below to a wanted tag, it shall be something like `vamb@3.0.1` in the end. (I don't know why they change their way of tagging).
https://github.com/metagenome-atlas/atlas/blob/059ab3f48eac971965f04067afbe9ffa73ef05c9/atlas/envs/vamb.yaml#L14
