### ISSUE TITLE
Host sequences removal

### ISSUE THREAD

**Issue by botellaflotante** [metagenome-atlas/atlas#493]
**I set in the config.yaml 3 genomes as host .fna files.  Like this:**

#contamination references can be added such that -- key: /path/to/fasta
contaminant_references:
  PhiX: /linuxhome/tmp/jose/databases/phiX174_virus.fa
  host1: /linuxhome/tmp/jose/host_genomes/GCF_000004075.3_Cucumber_9930_V3_genomic.fna
  host2: /linuxhome/tmp/jose/host_genomes/GCA_900231445.1_Triticum_turgidum.v1_genomic.fna
  host3: /linuxhome/tmp/jose/host_genomes/GCF_018294505.1_Triticum_aestivum_v2.1_genomic.fna

**But for some reason it gets stuck in the "rule build_decontamination_db:". It does not throw an error but it's been near 17 hs in that step without continuing
the log file is here.**
[build_decontamination_db.log](https://github.com/metagenome-atlas/atlas/files/7950487/build_decontamination_db.log)
**Is it possible these Triticum host sequences are too big and takes so long to process, or do you think it's another issue?
ls -l**
-rwxr-xr-x 1 jose binf 10088893922 Jan 25 01:34 GCA_900231445.1_Triticum_turgidum.v1_genomic.fna
-rwxr-xr-x 1 jose binf   229485246 Jan 25 01:34 GCF_000004075.3_Cucumber_9930_V3_genomic.fna
-rwxr-xr-x 1 jose binf   332600939 Jan 25 01:33 GCF_000317415.1_Citrus_sinensis_1.0_genomic.fna
-rwxr-xr-x 1 jose binf   538499827 Jan 25 01:33 GCF_000331145.1_Cicer_arietinum.fna
-rwxr-xr-x 1 jose binf   305340094 Jan 25 01:33 GCF_000493195.1_Citrus_clementina_v1.0_genomic.fna
-rwxr-xr-x 1 jose binf 14762960853 Jan 25 01:33 GCF_018294505.1_Triticum_aestivum_v2.1_genomic.fna

**Should I in that case increase the resorces for that particular step? this is now set
threads: 8
resources: mem=60, java_mem=51, time=5**

Best

**Comment by SilasK** [comment]
Sorry for the delay in replying. 

There is an error in the log file, but you say the pipline does not recognize it, or do you think it's due to the fact that cou killed the process? 
You don't run the job on a computational cluster, do you? Did you follow the documentation on local execution then?

Anyway I don't completely understand the error message from bbmap. But it could be related to the fact that your genomes ar huge.

You can definitively increase the memory and threads. Set `mem: 150` and `threads` to 12 or 16 in the `config.yaml`.

Wheat is huge and redundant isn't it? Is there a way to simplify the genomes? E.g. with dedupe.sh installed with atlas.

Other reccomendations. Use [BBmask](https://jgi.doe.gov/data-and-tools/bbtools/bb-tools-user-guide/bbmask-guide/) to preprocess your host genomes.

Also you might want to modify/add the parameters in the config file.

```
contaminant_ambiguous: best
contaminant_min_ratio: 0.9 # default 0.65 
contaminant_minimum_hits: 1
contaminant_max_indel: 1000 #default 20
```

Finaly you can check if your hosts are really in the samples by sacreening for them, but if you think they are this is not necessary. 

BTW: I suggest you rename the host1.. properly.

**Comment by botellaflotante** [comment]
Thanks for the answer. So, using:

contaminant_ambiguous: best
contaminant_min_ratio: 0.9 # default 0.65 
contaminant_minimum_hits: 1
contaminant_max_indel: 1000 #default 20
and 
mem: 150 and threads 16

did not solve it (it gets stucked at 45%). Could you indicate me how can I use dedupe.sh in ATLAS?

**Comment by SilasK** [comment]
I assume you don't have this issue anymore. Otherwise reopen or reply.
