### ISSUE TITLE
Error in rule error_correction

### ISSUE THREAD

**Issue by ChristophKnapp** [metagenome-atlas/atlas#545]
Hello, 
I'm trying to run the test data provided with metagenome-atlas. I just tried the code from getting started.

atlas init --db-dir databases test_reads >> all.out.txt 2>&1
atlas run all >> all.out.txt 2>&1

I attached the file I redirected all the output to, which gives some more information as the log file. Let me know in case you need more information. 

Thank you for your help.

[all.out.txt](https://github.com/metagenome-atlas/atlas/files/9337360/all.out.txt)

**Comment by ChristophKnapp** [comment]
Sorry for providing not enough information yesterday. I was very tired. Here is the error_correction.log file. It seems that it just run out of memory. Not sure how this can happen though, the computer this runs on has 128 Gb of RAM. Last I checked there was 118 still available. 51 Gb for the JVM seems reasonable too. 

Any idea whats going on?

Regards Christoph
[error_correction.log](https://github.com/metagenome-atlas/atlas/files/9348435/error_correction.log)

**Comment by SilasK** [comment]
The error correction is quite memory intensive. But on the test sample it should work with your resources. (I get it running on Google colab). My guess is that the different jobs of atlas or from other users are taking a bit too much memory so that it crashes. 

You can simply rerun atlas and see if it passes this step. 
Maybe decrease the maxmem parameter of atlas.
Don't you have a cluster system with more nodes? Because if you would run a real dataset you would barely be able to run one sample at a time, so you cannot benefit of parallelization. I mean it should be possible if your metagenome is not too complex/big but a cluster could definitely be useful. ( see the docs how to run atlas on a cluster).

**Comment by SilasK** [comment]
Did you solve the error?
