### ISSUE TITLE
Run atlas genomes without the taxonomy output

### ISSUE THREAD

**Issue by AnneliektH** [metagenome-atlas/atlas#705]
Hi, 

Id like to run atlas genomes, but without the taxonomy output. 
Im not interested in the gtdb classify and tree outputs, but I would like for my binning results to go through dRep and form the genomes output folder. 
I do know that I can turn off annotations in the config file. 
My problem is that I am working with around 150 individual datasets and I don't want to change each of the config files individually. 

Can I either run atlas init, and specify no-taxonomy, or are there specific rules in the snakemake file that I can comment out, so that the gtdb taxonomy is not done?

**Comment by SilasK** [comment]
Though atlas init creates a config file for each project, you can keep only one and then 
select which config file to use in the atlas run command with `--configfile`

To deactivate gtdb, and maybe dram (which is also heavy) comment modify the annotation section:

```
annotations:
  - genes
```
And keep only genes.


For note since one or two version I use skani for genome distance estimation and my own dereplication algorithm which has one or two additional steps than drep, but is not very different. (see past release notes)

These outputs are already available with the binning workflow.

Also, you might want to deactivate:
`rename_mags_contigs: true #Rename contigs of representative MAGs`
